### ISSUE TITLE
Add to cart functionality break  

### ISSUE THREAD

**Issue by biju-zoondia** [dev-Dhaval/Cart-File-Upload#1]
Hi,
We have installed this module on magento 2.3. while we clicking the add to cart button it shows the  /checkout/cart/ page with blank screen.

can you please give the solution for this issue?

Regards,

**Comment by dev-Dhaval** [comment]
can you please check a log file and provide related error?

**Comment by biju-zoondia** [comment]
Hi,
We have getting the error while running the compile command.

sudo php bin/magento setup:di:compile
Compilation was started.
Repositories code generation... 1/7 [====>-----------------------]  14% < 1 sec 76.5 MiBPHP Fatal error:  Cannot use Magento\Framework\Object as Object because 'Object' is a special class name in app/code/Eggwhite/Upload/Model/Upload.php on line 12

Regards,

**Comment by dev-Dhaval** [comment]
hey, i have update a code. Please check my last commit : f2aeabc39a863720d44a66c4e3d0c0e02abb78ce

please update and try to compile now.

**Comment by biju-zoondia** [comment]
Thanks for your reply.

The compilation issue fixed.

Current working functionality is in cart page. can we change this functionality to individual product page and added product images it shows in cart page based on the product in cart?

Regards,

**Comment by dev-Dhaval** [comment]
Currently this module is provide a feature only for cart page. Base on your requirement you have to modify this functionality.

Thanks

**Comment by biju-zoondia** [comment]
Thanks for your reply.
